// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLFAvenTFryt3gjSn8SfSKsNw04Z2gNjQ',
    appId: '1:913028209121:web:5084f5ae42187959a01aa0',
    messagingSenderId: '913028209121',
    projectId: 'quizapp-272d1',
    authDomain: 'quizapp-272d1.firebaseapp.com',
    storageBucket: 'quizapp-272d1.firebasestorage.app',
    measurementId: 'G-ZX2Z40JHML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxnJQ9U95TQaV_9cotjGZ2_HgvpgqejgM',
    appId: '1:913028209121:android:54a6842f00d766b8a01aa0',
    messagingSenderId: '913028209121',
    projectId: 'quizapp-272d1',
    storageBucket: 'quizapp-272d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADwF5Vj3yXYBFtjtCb_rs6g8E5bmIk-Cw',
    appId: '1:913028209121:ios:531c8fadcef458d5a01aa0',
    messagingSenderId: '913028209121',
    projectId: 'quizapp-272d1',
    storageBucket: 'quizapp-272d1.firebasestorage.app',
    androidClientId: '913028209121-c0u234i69iqqsbm2mml6dmg6o1g9dhuj.apps.googleusercontent.com',
    iosClientId: '913028209121-le15uugu29u5jacrk8h7fotl458hfroj.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADwF5Vj3yXYBFtjtCb_rs6g8E5bmIk-Cw',
    appId: '1:913028209121:ios:531c8fadcef458d5a01aa0',
    messagingSenderId: '913028209121',
    projectId: 'quizapp-272d1',
    storageBucket: 'quizapp-272d1.firebasestorage.app',
    androidClientId: '913028209121-c0u234i69iqqsbm2mml6dmg6o1g9dhuj.apps.googleusercontent.com',
    iosClientId: '913028209121-le15uugu29u5jacrk8h7fotl458hfroj.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLFAvenTFryt3gjSn8SfSKsNw04Z2gNjQ',
    appId: '1:913028209121:web:eb5de716c3266d22a01aa0',
    messagingSenderId: '913028209121',
    projectId: 'quizapp-272d1',
    authDomain: 'quizapp-272d1.firebaseapp.com',
    storageBucket: 'quizapp-272d1.firebasestorage.app',
    measurementId: 'G-9YGBFQ5CJR',
  );
}
